image: maven:3.8.6

definitions:
  steps:
    - step: &build-step
        name: Build and SonarQube analysis
        caches:
          - sonar
          - maven
        script:
          - mvn clean install  # Compiling the project to generate class files
          - pipe: sonarsource/sonarqube-scan:2.0.1
            variables:
              SONAR_HOST_URL: ${SONAR_HOST_URL}
              SONAR_TOKEN: ${SONAR_TOKEN}
              SONAR_SCANNER_OPTS: "-Dsonar.java.binaries=target/classes"  # Pointing to compiled classes
  caches:
    sonar: ~/.sonar
    maven: ~/.m2

pipelines:
  branches:
    '{main}':
      - step: *build-step
