app:
    base:
        url: ${PROD_BASE_URL}
    currency: IDR
    dev: true
    jwtExpirationInMs: ${PROD_JWT_EXPIRED}
    jwtSecret: ${PROD_JWT_SECRET}
    restrictCode: ${PROD_RESTRICT_CODE}
    timezone: Asia/Jakarta
mail:
    from: ${PROD_MAIL_FROM}
server:
    port: 8080
spring:
    datasource:
        hikari:
            connection-timeout: 600000
            idle-timeout: 600000
            max-lifetime: 1800000
            maximum-pool-size: 10
        password: ${PROD_DB_PASSWORD}
        url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
        username: ${PROD_DB_USERNAME}
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    batch_size: 100
                order_inserts: true
        show-sql: true
    mail:
        host: ${PROD_MAIL_HOST}
        password: ${PROD_MAIL_PASSWORD}
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: ${PROD_MAIL_USERNAME}
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
upload:
    dir: ${PROD_UPLOAD_DIR}
